### ISSUE TITLE
เกมไฟนอล

### ISSUE THREAD

**Issue by yositasatiman** [temty180447/G25#37]
https://drive.google.com/drive/folders/1oLUb8xetNt6lhmTN3B9lKFA9piq5-yL1?usp=sharing

**Comment by temty180447** [comment]
1.อยากให้แบบกดย่อก็ย่อถ้าปล่อยก็หายย่อเลย เวลากดย่อเสร็จเวลากลับมาตัวเท่าเดิมมันนานไป
2.อยากได้ตัวหนังสือบอกว่าอันไหน ความสามารถ ความชอบ เวลา ดวงบอกไว้ที่สกอด้านบนอะ
3.อยากได้ปุ่มเริ่มเกมใหม่ด้วย

**Comment by yositasatiman** [comment]
#งานล่าสุด2109 เก็บสำเร็จ ส่ง Test ครั้งแรก

[ https://teachablemachine.withgoogle.com/models/0p3iQ3uss/ ]
ยกแขน = Jump
กอดอก = shrink
อยู่นิ่ง = Idle

**Comment by yositasatiman** [comment]
#งานล่าสุด2609 เก็บสำเร็จ ส่ง Test ครั้งสอง

[ https://teachablemachine.withgoogle.com/models/LwBx5i80W/ ]
ยกแขน = Jump
กอดอก = shrink
อยู่นิ่ง = Idle

**Comment by yositasatiman** [comment]
ของเต็ม

https://teachablemachine.withgoogle.com/models/YOww4YOLb/

**Comment by yositasatiman** [comment]
#งานล่าสุด2709 00.07 เก็บสำเร็จ ส่ง Test ครั้งสาม

**Comment by yositasatiman** [comment]
https://teachablemachine.withgoogle.com/models/gDKKnw59C/

**Comment by yositasatiman** [comment]
#งานล่าสุด 2709 12.12 น. เก็บสำเร็จ ส่ง Test ครั้ง 4
