### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by yositasatiman** [temty180447/G25#38]

**Comment by yositasatiman** [comment]
ไดรฟ์สำหรับลงข้อมูลต่างๆ ใน Wiki
https://drive.google.com/drive/folders/1SMFVXkJRSibYynRgcBIIiLyyPZAR67iH?usp=sharing

**Comment by yositasatiman** [comment]
canva สำหรับ ทำงาน WiKi

https://www.canva.com/design/DAFvqIh0UJE/iHXssXWP4BODCIP4fP2Uig/edit?utm_content=DAFvqIh0UJE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Sweetypie28** [comment]
Evolution story link

https://scratch.mit.edu/projects/902308962
